import images from "./images";

const {
  azkaarItems,
  bakeryAndBreadItems,
  BeefDishes,
  beveragesItems,
  breakfastAndCerealItems,
  BreakfastItems,
  BrunchItems,
  ChickenItems,
  cleaningCaddyItems,
  condimentsAndDressingsItems,
  confectioneryAndSweetsItems,
  Cooking,
  cookingOilsItems,
  dairyAlternativesItems,
  DentalCare,
  DinnerItems,
  donatingItems,
  Eating,
  fastingItems,
  flourAndBakingSuppliesItems,
  frozenitems,
  fruitItems,
  grainsAndRiceItems,
  Haircare,
  herbsItems,
  LunchItems,
  meatAndSeafoodItems,
  meditationItems,
  milkproducts,
  NailCare,
  nutsAndSeedsItems,
  OfficialTask,
  paperProductsItems,
  pastaAndNoodlesItems,
  personalCareItems,
  PersonalHygiene,
  petFoodAndSuppliesItems,
  prayersItems,
  Pulses,
  SaladItems,
  sauces,
  SkinCare,
  snacksItems,
  spices,
  ToDoDrinking,
  ToDoLaundry,
  vegetableItems,
} = images;

export const MyListCollection = [
  {
    name: "Grocery List",
    image: "groceryImage",
    id: 1,
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { id: 1, name: "Bakery and Bread", items: bakeryAndBreadItems },
      { id: 2, name: "Beverages", items: beveragesItems },
      { id: 3, name: "Breakfast and Cereal", items: breakfastAndCerealItems },
      { id: 4, name: "Cleaning Caddy", items: cleaningCaddyItems },
      { id: 5, name: "Condiments and Dressings", items: condimentsAndDressingsItems },
      { id: 6, name: "Confectionery and Sweets", items: confectioneryAndSweetsItems },
      { id: 7, name: "Cooking Oils", items: cookingOilsItems },
      { id: 8, name: "Dairy Alternatives", items: dairyAlternativesItems },
      { id: 9, name: "Flour and Baking Supplies", items: flourAndBakingSuppliesItems },
      { id: 10, name: "Frozen Items", items: frozenitems },
      { id: 11, name: "Fruits", items: fruitItems },
      { id: 12, name: "Grains & Rice", items: grainsAndRiceItems },
      { id: 13, name: "Herbs", items: herbsItems },
      { id: 14, name: "Meat & Seafood", items: meatAndSeafoodItems },
      { id: 15, name: "Milk Products", items: milkproducts },
      { id: 16, name: "Nuts and Seeds", items: nutsAndSeedsItems },
      { id: 17, name: "Paper Products", items: paperProductsItems },
      { id: 18, name: "Pasta & Noodles", items: pastaAndNoodlesItems },
      { id: 19, name: "Personal Care", items: personalCareItems },
      { id: 20, name: "Pet Food and Supplies", items: petFoodAndSuppliesItems },
      { id: 21, name: "Pulses", items: Pulses },
      { id: 22, name: "Sauces", items: sauces },
      { id: 23, name: "Snacks", items: snacksItems },
      { id: 24, name: "Spices", items: spices },
      { id: 25, name: "Vegetables", items: vegetableItems },
    ]
  },
  {
    name: "Spiritual Goals",
    image: "spiritualImage",
    id: 2,
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { id: 1, name: "Prayers", items: prayersItems },
      { id: 2, name: "Fasting", items: fastingItems },
      { id: 3, name: "Donating", items: donatingItems },
      { id: 4, name: "Meditation", items: meditationItems },
      { id: 5, name: "Azkaar", items: azkaarItems },
    ],
  },
  {
    name: "Personal Grooming",
    image: "personalGroomingImage",
    id: 3,
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { id: 1, name: "Personal Hygiene", items: PersonalHygiene },
      { id: 2, name: "Dental Care", items: DentalCare },
      { id: 3, name: "Skin Care", items: SkinCare },
      { id: 4, name: "Hair Care", items: Haircare },
      { id: 5, name: "Nail Care", items: NailCare },
    ],
  },
  {
    name: "Things To Do",
    image: "thingsToDoImage",
    id: 4,
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { id: 1, name: "Cleaning", items: cleaningCaddyItems },
      { id: 2, name: "Laundry", items: ToDoLaundry },
      { id: 3, name: "Drinking", items: ToDoDrinking },
      { id: 4, name: "Eating", items: Eating },
      { id: 5, name: "Cooking", items: Cooking },
      { id: 6, name: "Official Tasks", items: OfficialTask },
    ],
  },
  {
    name: "Kitchen Menu",
    image: "kitchenMenuImage",
    id: 5,
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { id: 1, name: "Breakfast", items: BreakfastItems },
      { id: 2, name: "Brunch", items: BrunchItems },
      { id: 3, name: "Salads", items: SaladItems },
      { id: 4, name: "Chicken", items: ChickenItems },
      { id: 5, name: "Dinner", items: DinnerItems },
      { id: 6, name: "Lunch", items: LunchItems },
      { id: 7, name: "Beef", items: BeefDishes },
    ]
  }
]