import images from "./images";

const {
  azkaarItems,
  bakeryAndBreadItems,
  BeefDishes,
  beveragesItems,
  breakfastAndCerealItems,
  BreakfastItems,
  BrunchItems,
  ChickenItems,
  cleaningCaddyItems,
  condimentsAndDressingsItems,
  confectioneryAndSweetsItems,
  Cooking,
  cookingOilsItems,
  dairyAlternativesItems,
  DentalCare,
  DinnerItems,
  donatingItems,
  Eating,
  fastingItems,
  flourAndBakingSuppliesItems,
  frozenitems,
  fruitItems,
  grainsAndRiceItems,
  Haircare,
  herbsItems,
  LunchItems,
  meatAndSeafoodItems,
  meditationItems,
  milkproducts,
  NailCare,
  nutsAndSeedsItems,
  OfficialTask,
  paperProductsItems,
  pastaAndNoodlesItems,
  personalCareItems,
  PersonalHygiene,
  petFoodAndSuppliesItems,
  prayersItems,
  Pulses,
  SaladItems,
  sauces,
  SkinCare,
  snacksItems,
  spices,
  ToDoDrinking,
  ToDoLaundry,
  vegetableItems,
} = images;

export const MyListCollection = [
  {
    name: "Grocery List",
    image: "groceryImage",
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { name: "Bakery and Bread", items: bakeryAndBreadItems },
      { name: "Beverages", items: beveragesItems },
      { name: "Breakfast and Cereal", items: breakfastAndCerealItems },
      { name: "Cleaning Caddy", items: cleaningCaddyItems },
      { name: "Condiments and Dressings", items: condimentsAndDressingsItems },
      { name: "Confectionery and Sweets", items: confectioneryAndSweetsItems },
      { name: "Cooking Oils", items: cookingOilsItems },
      { name: "Dairy Alternatives", items: dairyAlternativesItems },
      { name: "Flour and Baking Supplies", items: flourAndBakingSuppliesItems },
      { name: "Frozen Items", items: frozenitems },
      { name: "Fruits", items: fruitItems },
      { name: "Grains & Rice", items: grainsAndRiceItems },
      { name: "Herbs", items: herbsItems },
      { name: "Meat & Seafood", items: meatAndSeafoodItems },
      { name: "Milk Products", items: milkproducts },
      { name: "Nuts and Seeds", items: nutsAndSeedsItems },
      { name: "Paper Products", items: paperProductsItems },
      { name: "Pasta & Noodles", items: pastaAndNoodlesItems },
      { name: "Personal Care", items: personalCareItems },
      { name: "Pet Food and Supplies", items: petFoodAndSuppliesItems },
      { name: "Pulses", items: Pulses },
      { name: "Sauces", items: sauces },
      { name: "Snacks", items: snacksItems },
      { name: "Spices", items: spices },
      { name: "Vegetables", items: vegetableItems },
    ],
  },
  {
    name: "Spiritual Goals",
    image: "spiritualImage",
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { name: "Prayers", items: prayersItems },
      { name: "Fasting", items: fastingItems },
      { name: "Donating", items: donatingItems },
      { name: "Meditation", items: meditationItems },
      { name: "Azkaar", items: azkaarItems },
    ],
  },
  {
    name: "Personal Grooming",
    image: "personalGroomingImage",
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { name: "Personal Hygiene", items: PersonalHygiene },
      { name: "Dental Care", items: DentalCare },
      { name: "Skin Care", items: SkinCare },
      { name: "Hair Care", items: Haircare },
      { name: "Nail Care", items: NailCare },
    ],
  },
  {
    name: "Things To Do",
    image: "thingsToDoImage",
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { name: "Cleaning", items: cleaningCaddyItems },
      { name: "Laundry", items: ToDoLaundry },
      { name: "Drinking", items: ToDoDrinking },
      { name: "Eating", items: Eating },
      { name: "Cooking", items: Cooking },
      { name: "Official Tasks", items: OfficialTask },
    ],
  },
  {
    name: "Kitchen Menu",
    image: "kitchenMenuImage",
    description:
      "Scroll to the predefined articles or type them freely into the search below.",
    Categories: [
      { name: "Breakfast", items: BreakfastItems },
      { name: "Brunch", items: BrunchItems },
      { name: "Salads", items: SaladItems },
      { name: "Chicken", items: ChickenItems },
      { name: "Dinner", items: DinnerItems },
      { name: "Lunch", items: LunchItems },
      { name: "Beef", items: BeefDishes },
    ],
  },
];
