const frozenitems = [
  { name: 'Bread', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Bread.png' },
  { name: 'Burger Patties', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Burger Patties.png' },
  { name: 'Cheese Ball', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Cheese Ball.png' },
  { name: 'Chicken Breast', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Chicken Breast.png' },
  { name: 'Chicken Samosa', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Chicken Samosa.png' },
  { name: 'Chicken Strips', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Chicken Strips.png' },
  { name: 'Chicken Wings', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Chicken Wings.png' },
  { name: 'Corn', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Corn.png' },
  { name: 'Dumplings', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Dumplings.png' },
  { name: 'Fish', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Fish.png' },
  { name: 'French Fries', imgPath: '/SwiftlistApp/Grocery/FrozenItems/French Fries.png' },
  { name: 'Fruits', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Fruits.png' },
  { name: 'Full Chicken', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Full Chicken.png' },
  { name: 'Gola Kebab', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Gola Kebab.png' },
  { name: 'Ice Cream', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Ice Cream.png' },
  { name: 'Meat', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Meat.png' },
  { name: 'Meatballs', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Meatballs.png' },
  { name: 'Nuggets', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Nuggets.png' },
  { name: 'Parathas', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Parathas.png' },
  { name: 'Pepperoni', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Peporoni.png' },
  { name: 'Pizza', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Pizza.png' },
  { name: 'Popcorn Chicken', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Popcorn Chicken.png' },
  { name: 'Sausages', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Sausages.png' },
  { name: 'Spring Roll', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Spring Roll.png' },
  { name: 'Vegetable Samosa', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Vegetable Samosa.png' },
  { name: 'Vegetables', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Vegetables.png' },
  { name: 'Wonton', imgPath: '/SwiftlistApp/Grocery/FrozenItems/Wonton.png' },
  { name: 'Chicken Drumstick', imgPath: '/SwiftlistApp/Grocery/FrozenItems/chicken_drumstick.png' },
];


const spices = [
  { name: 'Basil', imgPath: '/SwiftlistApp/Grocery/Spices/Basil.png' },
  { name: 'Black Cardamom', imgPath: '/SwiftlistApp/Grocery/Spices/Black Cardamom.png' },
  { name: 'Black Pepper', imgPath: '/SwiftlistApp/Grocery/Spices/Black Pepper.png' },
  { name: 'Cardamom', imgPath: '/SwiftlistApp/Grocery/Spices/Cardamom.png' },
  { name: 'Chilli Powder', imgPath: '/SwiftlistApp/Grocery/Spices/Chili Powder.png' },
  { name: 'Cinnamon', imgPath: '/SwiftlistApp/Grocery/Spices/Cinnamon.png' },
  { name: 'Cloves', imgPath: '/SwiftlistApp/Grocery/Spices/Cloves.png' },
  { name: 'Coriander Powder', imgPath: '/SwiftlistApp/Grocery/Spices/Coriander Powder.png' },
  { name: 'Cumin', imgPath: '/SwiftlistApp/Grocery/Spices/Cumin.png' },
  { name: 'Curry Leaves', imgPath: '/SwiftlistApp/Grocery/Spices/Curry Leaves.png' },
  { name: 'Fennel Seeds', imgPath: '/SwiftlistApp/Grocery/Spices/Fennel Seeds.png' },
  { name: 'Garam Masala', imgPath: '/SwiftlistApp/Grocery/Spices/Garam Masala.png' },
  { name: 'Garlic Powder', imgPath: '/SwiftlistApp/Grocery/Spices/Garlic Powder.png' },
  { name: 'Ginger Powder', imgPath: '/SwiftlistApp/Grocery/Spices/Ginger Powder.png' },
  { name: 'Mixed Herbs', imgPath: '/SwiftlistApp/Grocery/Spices/Mixed Herbs.png' },
  { name: 'Nutmeg', imgPath: '/SwiftlistApp/Grocery/Spices/Nutmeg.png' },
  { name: 'Oregano', imgPath: '/SwiftlistApp/Grocery/Spices/Oregano.png' },
  { name: 'Paprika Powder', imgPath: '/SwiftlistApp/Grocery/Spices/Paprika Powder.png' },
  { name: 'Powdered Garam Masala', imgPath: '/SwiftlistApp/Grocery/Spices/Powdered Garam Masala.png' },
  { name: 'Red Chilli Flakes', imgPath: '/SwiftlistApp/Grocery/Spices/Red Chilli Flakes.png' },
  { name: 'Rosemary', imgPath: '/SwiftlistApp/Grocery/Spices/Rosemary.png' },
  { name: 'Salt', imgPath: '/SwiftlistApp/Grocery/Spices/Salt.png' },
  { name: 'Star Anise', imgPath: '/SwiftlistApp/Grocery/Spices/Star Anise.png' },
  { name: 'Sugar', imgPath: '/SwiftlistApp/Grocery/Spices/Sugar.png' },
  { name: 'Turmeric Powder', imgPath: '/SwiftlistApp/Grocery/Spices/Turmeric Powder.png' },
  { name: 'White Pepper', imgPath: '/SwiftlistApp/Grocery/Spices/White Pepper.png' },
];


const sauces = [
  { name: 'BBQ Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/BBQ Sauce.png' },
  { name: 'Balsamic Vinegar', imgPath: '/SwiftlistApp/Grocery/Sauces/Balsamic Vinegar.png' },
  { name: 'Chili Paste', imgPath: '/SwiftlistApp/Grocery/Sauces/Chili Paste.png' },
  { name: 'Chilli Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Chilli Sauce.png' },
  { name: 'Fish Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Fish Sauce.png' },
  { name: 'Hot Chilli Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Hot Chilli Sauce.png' },
  { name: 'Hot Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Hot Sauce.png' },
  { name: 'Marinara Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Marinara Sauce.png' },
  { name: 'Mayonnaise', imgPath: '/SwiftlistApp/Grocery/Sauces/Mayonnaise.png' },
  { name: 'Mustard Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Mustard Sauce.png' },
  { name: 'Pasta Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Pasta Sauce.png' },
  { name: 'Seasoning Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Seasoning Sauce.png' },
  { name: 'Soy Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Soy Sauce.png' },
  { name: 'Sriracha', imgPath: '/SwiftlistApp/Grocery/Sauces/Sriracha.png' },
  { name: 'Steak Sauce', imgPath: '/SwiftlistApp/Grocery/Sauces/Steak Sauce.png' },
  { name: 'Tahini', imgPath: '/SwiftlistApp/Grocery/Sauces/Tahini.png' },
  { name: 'Tomato Paste', imgPath: '/SwiftlistApp/Grocery/Sauces/Tomato Paste.png' },
  { name: 'Vinegar', imgPath: '/SwiftlistApp/Grocery/Sauces/Vinegar.png' },
  { name: 'Ketchup', imgPath: '/SwiftlistApp/Grocery/Sauces/ketchup.png' },
];


const milkproducts = [
  { name: 'Butter Milk', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Butter Milk.png' },
  { name: 'Butter', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Butter.png' },
  { name: 'Cheese', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Cheese.png' },
  { name: 'Condensed Milk', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Condensed Milk.png' },
  { name: 'Cottage Cheese', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Cottage Cheese.png' },
  { name: 'Cream Cheese', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Cream Cheese.png' },
  { name: 'Cream', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Cream.png' },
  { name: 'Evaporated Milk', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Evaporated Milk.png' },
  { name: 'Heavy Cream', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Heavy Cream.png' },
  { name: 'Skim Milk', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Skim Milk.png' },
  { name: 'Sour Cream', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Sour Cream.png' },
  { name: 'Whole Milk Powder', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Whole Milk Powder.png' },
  { name: 'Whole Milk', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Whole Milk.png' },
  { name: 'Yogurt', imgPath: '/SwiftlistApp/Grocery/MilkProducts/Yogurt.png' },
];


const vegetableItems = [
  { name: 'Potato', imgPath: '/SwiftlistApp/Grocery/vegetables/Potato.png' },
  { name: 'Bringle', imgPath: '/SwiftlistApp/Grocery/vegetables/bringle.png' },
  { name: 'Broccoli', imgPath: '/SwiftlistApp/Grocery/vegetables/brocolli.png' },
  { name: 'Cabbage', imgPath: '/SwiftlistApp/Grocery/vegetables/cabbage.png' },
  { name: 'Capsicum', imgPath: '/SwiftlistApp/Grocery/vegetables/capsicum.png' },
  { name: 'Carrot', imgPath: '/SwiftlistApp/Grocery/vegetables/carrot.png' },
  { name: 'Cucumber', imgPath: '/SwiftlistApp/Grocery/vegetables/cucumber.png' },
  { name: 'Garlic', imgPath: '/SwiftlistApp/Grocery/vegetables/garlic.png' },
  { name: 'Ginger', imgPath: '/SwiftlistApp/Grocery/vegetables/ginger.png' },
  { name: 'Green Beans', imgPath: '/SwiftlistApp/Grocery/vegetables/green_beans.png' },
  { name: 'Green Chilli', imgPath: '/SwiftlistApp/Grocery/vegetables/greenchilli.png' },
  { name: 'Leek', imgPath: '/SwiftlistApp/Grocery/vegetables/leek.png' },
  { name: 'Lettuce', imgPath: '/SwiftlistApp/Grocery/vegetables/lettuce.png' },
  { name: 'Mushroom', imgPath: '/SwiftlistApp/Grocery/vegetables/mushroom.png' },
  { name: 'Okra', imgPath: '/SwiftlistApp/Grocery/vegetables/okra.png' },
  { name: 'Onion', imgPath: '/SwiftlistApp/Grocery/vegetables/onion.png' },
  { name: 'Peas', imgPath: '/SwiftlistApp/Grocery/vegetables/peas.png' },
  { name: 'Spinach', imgPath: '/SwiftlistApp/Grocery/vegetables/spinach.png' },
  { name: 'Sweet Potato', imgPath: '/SwiftlistApp/Grocery/vegetables/sweetpotato.png' },
  { name: 'Tomato', imgPath: '/SwiftlistApp/Grocery/vegetables/tomatoo.png' },
  { name: 'Turnip', imgPath: '/SwiftlistApp/Grocery/vegetables/turnipp.png' },
  { name: 'Zucchini', imgPath: '/SwiftlistApp/Grocery/vegetables/zucchinii.png' }
];



// // Fruit items
const fruitItems = [
  { imgPath: 'SwiftlistApp/Grocery/fruits/apple.png', name: 'Apple' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/avocado.png', name: 'Avocado' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/banana.png', name: 'Banana' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/blueberry.png', name: 'Blueberry' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/cherry.png', name: 'Cherry' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/grapes.png', name: 'Grapes' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/guava.png', name: 'Guava' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/kiwi.png', name: 'Kiwi' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/lichi.png', name: 'Lichi' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/mango.png', name: 'Mango' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/melon.png', name: 'Melon' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/orange.png', name: 'Orange' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/papaya.png', name: 'Papaya' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/peach.png', name: 'Peach' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/pear.png', name: 'Pear' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/pineapple.png', name: 'Pineapple' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/pomengarate.png', name: 'Pomengranate' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/raspberry.png', name: 'Raspberry' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/strawberry.png', name: 'Strawberry' },
  { imgPath: 'SwiftlistApp/Grocery/fruits/watermelon.png', name: 'Watermelon' },
];


export {frozenitems , spices , sauces , milkproducts , vegetableItems , fruitItems};
// export {fruitItems, vegetableItems, milkproducts, sauces, spices, frozenitems};
